  METHOD ENSURE_CONFIG.
    IF MV_HTTP_DEST IS NOT INITIAL
    AND MV_OAUTH_TOKEN_PATH IS NOT INITIAL
    AND MV_LOTES_PATH IS NOT INITIAL
    AND MV_TIMEOUT_SEC > 0.
      RETURN.
    ENDIF.

    TRY.
        ME->LOAD_PARAMS_STRICT( ).
      CATCH ZCX_THOM_CFG.
        RAISE EXCEPTION TYPE ZCX_THOM_CFG.
    ENDTRY.
  ENDMETHOD.
