  METHOD GET_TVARVC_PARAM.
    DATA LS_TVARVC TYPE TVARVC.

    CLEAR EV_VALUE.

    SELECT SINGLE *
    INTO LS_TVARVC
    FROM TVARVC
    WHERE NAME = IV_NAME
    AND TYPE = 'P'.

    IF SY-SUBRC = 0.
      EV_VALUE = LS_TVARVC-LOW.
    ENDIF.
  ENDMETHOD.
