CLASS ZCL_THOM_HELPER DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS CHECK_CONS_GERAL
      IMPORTING
        IV_CENTRO TYPE WERKS_D
        IV_DEPOS  TYPE LGORT_D
        IV_MATNR  TYPE MATNR
        IV_OBJ    TYPE BALOBJ_D
        IV_SUBOBJ TYPE BALSUBOBJ
      EXPORTING
        EV_SEND   TYPE BOOLEAN.
