METHOD _UPDATE_COCKPIT_STATUS.

  DATA LS_STATUS TYPE ZCR_TB_WS_STATUS. "ajusta para o tipo real do teu S_STATUS

  CLEAR: ES_MESSAGE, LS_STATUS.

*  S_STATUS-WS_GUID_SAP = IV_WS_GUID_SAP.

  IF IV_OK = ABAP_TRUE.
    S_STATUS-STATUS = ZCR_CL_INTF_GEN=>C_WS_STATUS_SUC.
  ELSE.
    S_STATUS-STATUS = ZCR_CL_INTF_GEN=>C_WS_STATUS_ERR.
  ENDIF.

  "Se existir campo de mensagem no status do cockpit, seta aqui
  S_STATUS-MESSAGE = IV_MESSAGE.

  ZCR_CL_INTF_GEN=>UPDATE_STATUS_WS(
  IMPORTING
    ES_MESSAGE = ES_MESSAGE
  CHANGING
    CS_STATUS  = S_STATUS ).

  IF ES_MESSAGE IS NOT INITIAL.
    MO_LOG->ADD_FROM_BAPI( IS_BAPIRET = ES_MESSAGE ).
  ENDIF.

  MO_LOG->STORE( ).
ENDMETHOD.
