" Método: HTTP_POST_JSON
METHOD HTTP_POST_JSON.
  DATA: LO_HTTP   TYPE REF TO IF_HTTP_CLIENT,
        LV_CODE   TYPE I,
        LV_REASON TYPE STRING,
        LV_AUTH   TYPE STRING,
        LV_USERPW TYPE STRING,
        LV_B64    TYPE STRING,
        LO_CX     TYPE REF TO CX_ROOT.

  CLEAR: EV_HTTP_CODE, EV_RESPONSE.

  TRY.
      CL_HTTP_CLIENT=>CREATE_BY_DESTINATION(
      EXPORTING DESTINATION = IV_DEST
      IMPORTING CLIENT      = LO_HTTP ).
    CATCH CX_ROOT INTO LO_CX.
      EV_HTTP_CODE = 0.
      EV_RESPONSE  = LO_CX->GET_TEXT( ).
      RETURN.
  ENDTRY.

  "Evitar popup
  TRY.
      LO_HTTP->PROPERTYTYPE_LOGON_POPUP = LO_HTTP->CO_DISABLED.
    CATCH CX_ROOT.
  ENDTRY.

  "URI
  IF IV_PATH IS NOT INITIAL.
    TRY.
        CL_HTTP_UTILITY=>SET_REQUEST_URI(
        REQUEST = LO_HTTP->REQUEST
        URI     = IV_PATH ).
      CATCH CX_ROOT INTO LO_CX.
        EV_HTTP_CODE = 0.
        EV_RESPONSE  = LO_CX->GET_TEXT( ).
        TRY.
            LO_HTTP->CLOSE( ).
          CATCH CX_ROOT.
        ENDTRY.
        RETURN.
    ENDTRY.
  ENDIF.

  LO_HTTP->REQUEST->SET_METHOD( IF_HTTP_REQUEST=>CO_REQUEST_METHOD_POST ).
  LO_HTTP->REQUEST->SET_HEADER_FIELD( NAME = 'Content-Type' VALUE = 'application/json' ).
  LO_HTTP->REQUEST->SET_HEADER_FIELD( NAME = 'Accept'       VALUE = 'application/json' ).

  "Auth: Basic primeiro
  IF IV_USER IS NOT INITIAL OR IV_PASS IS NOT INITIAL.
    CONCATENATE IV_USER IV_PASS INTO LV_USERPW SEPARATED BY ':'.
    TRY.
        LV_B64 = CL_HTTP_UTILITY=>ENCODE_BASE64( UNENCODED = LV_USERPW ).
        CONCATENATE 'Basic' LV_B64 INTO LV_AUTH SEPARATED BY SPACE.
        LO_HTTP->REQUEST->SET_HEADER_FIELD( NAME = 'Authorization' VALUE = LV_AUTH ).
      CATCH CX_ROOT.
        "sem dump
    ENDTRY.
  ELSEIF IV_BEARER IS NOT INITIAL.
    CONCATENATE 'Bearer' IV_BEARER INTO LV_AUTH SEPARATED BY SPACE.
    LO_HTTP->REQUEST->SET_HEADER_FIELD( NAME = 'Authorization' VALUE = LV_AUTH ).
  ENDIF.

  LO_HTTP->REQUEST->SET_CDATA( IV_JSON ).

  TRY.
      LO_HTTP->SEND( TIMEOUT = IV_TIMEOUT ).
      LO_HTTP->RECEIVE(
      EXCEPTIONS
        HTTP_COMMUNICATION_FAILURE = 1
        HTTP_INVALID_STATE         = 2
        HTTP_PROCESSING_FAILED     = 3
        OTHERS                     = 4  ).

      LO_HTTP->RESPONSE->GET_STATUS( IMPORTING CODE = LV_CODE REASON = LV_REASON ).
      EV_HTTP_CODE = LV_CODE.
      EV_RESPONSE  = LO_HTTP->RESPONSE->GET_CDATA( ).
    CATCH CX_ROOT INTO LO_CX.
      EV_HTTP_CODE = 0.
      EV_RESPONSE  = LO_CX->GET_TEXT( ).
  ENDTRY.

  TRY.
      LO_HTTP->CLOSE( ).
    CATCH CX_ROOT.
  ENDTRY.
ENDMETHOD.
