  METHOD _FINISH_ERROR.
    DATA: LS_MESSAGE  TYPE ZCR_S_WS_OUTPUT, "BAPIRET2,
          LV_TS       TYPE TIMESTAMPL,
          LV_MSG50    TYPE SYMSGV,
          LV_ATTEMPTS TYPE I.

    GET TIME STAMP FIELD LV_TS.

    LV_ATTEMPTS = IV_ATTEMPTS.
    IF LV_ATTEMPTS IS INITIAL.
      LV_ATTEMPTS = 1.
    ENDIF.

    LV_MSG50 = IV_MESSAGE.

    ME->_UPDATE_AFTER_SEND(
    EXPORTING
      IV_WS_GUID_SAP = IV_INTERF_ID
      IV_STATUS      = C_ST_ERROR
      IV_HTTP_CODE   = IV_HTTP_CODE
      IV_MESSAGE     = IV_MESSAGE
      IV_ATTEMPTS    = LV_ATTEMPTS
      IV_SENT_TS     = LV_TS
      IV_RESPONSE_X  = IV_RESPONSEX ).

    MO_LOG->ADD(
    EXPORTING
      ID_MSGTY = 'E'
      ID_MSGID = 'ZTHOM'
      ID_MSGNO = '011'
      ID_MSGV1 = LV_MSG50 ).


    LS_MESSAGE = ME->BUILD_BAPIRET2(
    IV_TYPE   = 'E'
    IV_ID     = 'ZTHOM'
    IV_NUMBER = '011'
    IV_V1     = LV_MSG50 ).

    SELECT SINGLE * FROM ZCR_TB_WS_STATUS INTO S_STATUS
    WHERE WS_GUID_SAP EQ IV_INTERF_ID.

    IF SY-SUBRC EQ 0.
      S_STATUS-MESSAGE  = LS_MESSAGE-MESSAGE.
      S_STATUS-STATUS   = ZCR_CL_INTF_GEN=>C_WS_STATUS_ERR.
      S_STATUS-WSID     = 131.

      UPDATE ZCR_TB_WS_STATUS SET WSID    = 131
                                  STATUS  = ZCR_CL_INTF_GEN=>C_WS_STATUS_ERR
                                  MESSAGE = LS_MESSAGE-MESSAGE
                                  WHERE WS_GUID_SAP = IV_INTERF_ID.
      IF SY-SUBRC EQ 0.
        COMMIT WORK AND WAIT.
      ENDIF.

    ENDIF.
    ZCR_CL_INTF_GEN=>UPDATE_STATUS_WS(
    IMPORTING
      ES_MESSAGE = LS_MESSAGE
    CHANGING
      CS_STATUS  = S_STATUS ).

    IF LS_MESSAGE IS NOT INITIAL.
      MO_LOG->ADD_FROM_BAPI( IS_BAPIRET = LS_MESSAGE ).
    ENDIF.

    MO_LOG->STORE( ).
    COMMIT WORK AND WAIT.
  ENDMETHOD.
