  METHOD _FINISH_SUCCESS.
    DATA: LS_MESSAGE TYPE BAPIRET2,
          LV_TS      TYPE TIMESTAMPL,
          LV_MSGV1   TYPE SYMSGV.

    GET TIME STAMP FIELD LV_TS.

    ME->_UPDATE_AFTER_SEND(
    EXPORTING
      IV_WS_GUID_SAP = IV_INTERF_ID
      IV_STATUS      = C_ST_SENT
      IV_HTTP_CODE   = IV_HTTP_CODE
      IV_MESSAGE     = ''
      IV_ATTEMPTS    = IV_ATTEMPTS
      IV_SENT_TS     = LV_TS
      IV_RESPONSE_X  = IV_RESPONSEX ).


    LS_MESSAGE = ME->BUILD_BAPIRET2(
    IV_TYPE   = 'S'
    IV_ID     = 'ZTHOM'
    IV_NUMBER = '010'
    IV_V1     = LV_MSGV1 ).

    SELECT SINGLE * FROM ZCR_TB_WS_STATUS INTO S_STATUS
    WHERE WS_GUID_SAP EQ IV_INTERF_ID.

    IF SY-SUBRC EQ 0.
      S_STATUS-STATUS   = ZCR_CL_INTF_GEN=>C_WS_STATUS_SUC.
      S_STATUS-WSID     = 131.

      UPDATE ZCR_TB_WS_STATUS SET WSID    = 131
                                  STATUS  = ZCR_CL_INTF_GEN=>C_WS_STATUS_SUC
      WHERE WS_GUID_SAP = IV_INTERF_ID.
      IF SY-SUBRC EQ 0.
        COMMIT WORK AND WAIT.
      ENDIF.
    ENDIF.

    ZCR_CL_INTF_GEN=>UPDATE_STATUS_WS(
    IMPORTING
      ES_MESSAGE = LS_MESSAGE
    CHANGING
      CS_STATUS  = S_STATUS ).

    IF LS_MESSAGE IS NOT INITIAL.
      MO_LOG->ADD_FROM_BAPI( IS_BAPIRET = LS_MESSAGE ).
    ENDIF.

    MO_LOG->STORE( ).
    COMMIT WORK AND WAIT.

  ENDMETHOD.
