  METHOD _BUILD_LOTE_PAYLOAD.
    DATA: LV_MAT_OUT TYPE STRING,
          LV_VF_ISO  TYPE STRING,
          LV_CLABS   TYPE STRING,
          LV_OK      TYPE ABAP_BOOL,
          LV_MSG     TYPE STRING.

    CLEAR: ES_PAYLOAD,
    EV_OK,
    EV_MESSAGE,
    LV_MAT_OUT,
    LV_VF_ISO,
    LV_CLABS,
    LV_OK,
    LV_MSG.

    ES_PAYLOAD-EVENT_TYPE = IV_EVENT_CUI.

    CALL FUNCTION 'CONVERSION_EXIT_MATN1_OUTPUT'
      EXPORTING
        INPUT  = IS_DB-MATNR
      IMPORTING
        OUTPUT = LV_MAT_OUT.

    IF LV_MAT_OUT IS INITIAL.
      LV_MAT_OUT = IS_DB-MATNR.
    ENDIF.

    ES_PAYLOAD-MATNR = LV_MAT_OUT.
    ES_PAYLOAD-CHARG = IS_DB-CHARG.
    ES_PAYLOAD-WERKS = IS_DB-WERKS.
    ES_PAYLOAD-LGORT = IS_DB-LGORT.

    ME->_FORMAT_VFDAT_ISO(
    EXPORTING
      IV_VFDAT   = IS_DB-VFDAT
    IMPORTING
      EV_VFDAT   = LV_VF_ISO
      EV_OK      = LV_OK
      EV_MESSAGE = LV_MSG ).

    IF LV_OK <> ABAP_TRUE.
      EV_OK      = LV_OK.
      EV_MESSAGE = LV_MSG.
      RETURN.
    ENDIF.

    ES_PAYLOAD-VFDAT = LV_VF_ISO.

    ME->_FORMAT_CLABS_STRING(
    EXPORTING
      IV_CLABS = IS_DB-CLABS
    IMPORTING
      EV_CLABS = LV_CLABS ).


    LV_CLABS = ZCL_THOM_INTERF_LOTE=>NORMALIZE_AMOUNT_FOR_JSON( IV_VALUE = LV_CLABS ).
    ES_PAYLOAD-CLABS = LV_CLABS.

    EV_OK = ABAP_TRUE.
  ENDMETHOD.
