  METHOD CHECK_SENT_BATCH.
    DATA: LV_MATNR_DB TYPE MATNR,
          LV_EXISTS   TYPE C LENGTH 1.

    CLEAR: LV_MATNR_DB, LV_EXISTS.
    EV_SENT = ABAP_FALSE.

    "MATNR18 -> MATNR (ALPHA IN)
    LV_MATNR_DB = IV_MATNR.
    CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
      EXPORTING
        INPUT  = LV_MATNR_DB
      IMPORTING
        OUTPUT = LV_MATNR_DB
      EXCEPTIONS
        OTHERS = 1.

    IF IV_LGORT IS INITIAL.

      SELECT SINGLE 'X'
      INTO @LV_EXISTS
      FROM ZTHOM_INTERF_LOT
      WHERE MATNR  = @LV_MATNR_DB
      AND WERKS  = @IV_WERKS
      AND CHARG  = @IV_CHARG
      AND STATUS = 'SENT'.

    ELSE.

      SELECT SINGLE 'X'
      INTO @LV_EXISTS
      FROM ZTHOM_INTERF_LOT
      WHERE MATNR  = @LV_MATNR_DB
      AND WERKS  = @IV_WERKS
      AND LGORT  = @IV_LGORT
      AND CHARG  = @IV_CHARG
      AND STATUS = 'SENT'.

    ENDIF.

    IF SY-SUBRC = 0 AND LV_EXISTS = 'X'.
      EV_SENT = ABAP_TRUE.
    ENDIF.
  ENDMETHOD.
