METHOD CALC_SHA256_HEX64.
  DATA: LV_SHA_X TYPE XSTRING,
        LT_BIN   TYPE SOLIX_TAB,
        LS_BIN   TYPE SOLIX,
        LV_INT   TYPE I,
        LV_HI    TYPE I,
        LV_LO    TYPE I,
        LV_HEX   TYPE STRING.

  CONSTANTS: LC_HEXMAP TYPE STRING VALUE '0123456789ABCDEF'.

  CLEAR: EV_HASH64, LV_SHA_X, LT_BIN, LV_HEX.

  "SHA-256 em RAW (XSTRING 32 bytes)
  TRY.
      CALL METHOD CL_ABAP_MESSAGE_DIGEST=>CALCULATE_HASH_FOR_RAW
        EXPORTING
          IF_ALGORITHM = 'SHA-256'
          IF_DATA      = IV_XSTR
        IMPORTING
          EF_HASHX     = LV_SHA_X.   "atenção: EF_HASHX
    CATCH CX_ROOT.
      CLEAR LV_SHA_X.
  ENDTRY.

  IF LV_SHA_X IS INITIAL.
    RETURN.
  ENDIF.

  "XSTRING -> bytes (SOLIX)
  CALL FUNCTION 'SCMS_XSTRING_TO_BINARY'
    EXPORTING
      BUFFER     = LV_SHA_X
    TABLES
      BINARY_TAB = LT_BIN.

  "bytes -> HEX (64 chars)
  LOOP AT LT_BIN INTO LS_BIN.
    LV_INT = LS_BIN-LINE.
    LV_HI  = LV_INT DIV 16.
    LV_LO  = LV_INT MOD 16.

    CONCATENATE LV_HEX
    LC_HEXMAP+LV_HI(1)
    LC_HEXMAP+LV_LO(1)
    INTO LV_HEX
    RESPECTING BLANKS.
  ENDLOOP.

  EV_HASH64 = LV_HEX.
ENDMETHOD.
