  METHOD _FORMAT_CLABS_STRING.
    DATA LV_CLABS_C TYPE C LENGTH 30.

    CLEAR: EV_CLABS,
    LV_CLABS_C.

    WRITE IV_CLABS TO LV_CLABS_C.
    SHIFT LV_CLABS_C LEFT DELETING LEADING SPACE.
    CONDENSE LV_CLABS_C NO-GAPS.
    REPLACE ALL OCCURRENCES OF ',' IN LV_CLABS_C WITH '.'.

    IF LV_CLABS_C IS INITIAL.
      EV_CLABS = '0'.
    ELSE.
      EV_CLABS = LV_CLABS_C.
    ENDIF.
  ENDMETHOD.
