METHOD ZCR_IF_INTF~CALL_ADD_STEP.

  DATA LS_ZTHOM_ENMAT TYPE ZTHOM_ENMAT.

  FIELD-SYMBOLS:
    <LT_INPUT> TYPE STANDARD TABLE,
    <LS_INPUT> TYPE ANY.

  TRY.
      ASSIGN ID_INPUT->* TO <LT_INPUT>.
    CATCH CX_SY_ASSIGN_CAST_ILLEGAL_CAST
      CX_SY_ASSIGN_CAST_UNKNOWN_TYPE
      CX_SY_ASSIGN_OUT_OF_RANGE.
  ENDTRY.

  IF <LT_INPUT> IS NOT ASSIGNED.

    ES_MESSAGE = ZCR_CL_INTF_GEN=>FILL_BAPIRET( IV_MSGID = 'ZCR'
    IV_MSGTY = 'E'
    IV_MSGNO = '011'
    IV_MSGV1 = CONV #( S_STATUS-WSID )
    IV_MSGV2 = CONV #( ZCR_CL_INTF_GEN=>GET_WS_ID_DESCRIPTION( S_STATUS-WSID ) ) ).

    IF IV_NEW_LOG = ABAP_TRUE.
      MO_LOG = ZCR_CL_INTF_GEN=>GET_INSTANCE_LOG( IV_OBJECT    = IV_OBJECT
      IV_SUBOBJECT = IV_SUBOBJECT
      IV_EXTNUMBER = IV_EXTNUMBER
      IV_NEW_LOG   = ABAP_TRUE ).
    ENDIF.

    MO_LOG->ADD_FROM_BAPI( IS_BAPIRET = ES_MESSAGE ).
    MO_LOG->STORE( ).
    IF V_COMMIT EQ ABAP_TRUE.
      COMMIT WORK AND WAIT.
    ENDIF.
    RETURN.
  ENDIF.

  READ TABLE <LT_INPUT> ASSIGNING <LS_INPUT> INDEX 1.
  IF SY-SUBRC <> 0.
    " tabela vazia
    RETURN.
  ENDIF.
  MOVE-CORRESPONDING <LS_INPUT> TO LS_ZTHOM_ENMAT.
*  LS_ZTHOM_ENMAT = <LS_INPUT>.

  MO_LOG = ZCR_CL_INTF_GEN=>GET_INSTANCE_LOG( EXPORTING IV_OBJECT    = IV_OBJECT
    IV_SUBOBJECT = IV_SUBOBJECT
    IV_EXTNUMBER = ZCR_CL_INTF_GEN=>GET_LOG_EXTNUMBER( IV_EXTNUMBER   = IV_EXTNUMBER
    IV_WS_GUID_SAP = LS_ZTHOM_ENMAT-WS_GUID_SAP )
    IV_NEW_LOG   = ABAP_TRUE ).


  PROCESS(
  EXPORTING
    I_WERKS = LS_ZTHOM_ENMAT-WERKS
    I_LGORT = LS_ZTHOM_ENMAT-LGORT
    I_MATNR = LS_ZTHOM_ENMAT-MATNR
    I_EVENT_TYPE = LS_ZTHOM_ENMAT-EVENT_TYPE
    I_REPROCESS = ABAP_TRUE
    ).
ENDMETHOD.
