  METHOD LOAD_PARAMS_STRICT.
    DATA: LS_EP TYPE ZTHOM_ENDPOINTS,
          LO_CX TYPE REF TO CX_ROOT.

    CLEAR: MV_HTTP_DEST, MV_LOTES_PATH, MV_TIMEOUT_SEC,
    MV_AUTH_USER, MV_AUTH_PASS,
    MV_LAST_CFG_SERVICE, MV_LAST_CFG_MESSAGE.

    TRY.
        ME->GET_ENDPOINT(
        EXPORTING
          IV_SERVICE_ID = 'LOTES'
        IMPORTING
          ES_EP         = LS_EP ).

        IF LS_EP-SERVICE_ID IS INITIAL.
          "GET_ENDPOINT já setou MV_LAST_CFG_MESSAGE
          RETURN.
        ENDIF.

        "Ajusta nomes conforme SE11:
        MV_HTTP_DEST   = LS_EP-DEST_SM59.
        MV_LOTES_PATH  = LS_EP-RESOURCE_PATH.
        MV_TIMEOUT_SEC = LS_EP-TIMEOUT_SEC.

        MV_AUTH_USER   = LS_EP-AUTH_USER.
        MV_AUTH_PASS   = LS_EP-AUTH_PASS.

      CATCH CX_ROOT INTO LO_CX.
        MV_LAST_CFG_SERVICE = 'LOTES'.
        MV_LAST_CFG_MESSAGE = LO_CX->GET_TEXT( ).
        CLEAR: MV_HTTP_DEST, MV_LOTES_PATH, MV_TIMEOUT_SEC, MV_AUTH_USER, MV_AUTH_PASS.
    ENDTRY.
  ENDMETHOD.
