METHOD CHECK_SERVICE_AVAILABLE.

  DATA LS_EP TYPE ZTHOM_ENDPOINTS.

  RV_OK = ABAP_FALSE.

  CLEAR: MV_LAST_CFG_SERVICE,
  MV_LAST_CFG_MESSAGE.

  IF MV_ENV IS INITIAL.
    ME->SET_ENV( ).
  ENDIF.

  ME->GET_ENDPOINT(
  EXPORTING
    IV_SERVICE_ID = IV_SERVICE_ID
  IMPORTING
    ES_EP         = LS_EP ).

  IF LS_EP IS INITIAL.
    RETURN.
  ENDIF.

  "Ajustar o nome do campo se não for ENDPOINT
  IF LS_EP-ACTIVE ne abap_true.
    MV_LAST_CFG_SERVICE = IV_SERVICE_ID.
    MV_LAST_CFG_MESSAGE = |Serviço { IV_SERVICE_ID } com endpoint vazio NO ambiente { MV_ENV }|.
    RETURN.
  ENDIF.

  RV_OK = ABAP_TRUE.

ENDMETHOD.
